### ISSUE TITLE
怎么换节点

### ISSUE THREAD

**Issue by vb3328998** [ghostxu97/clash-for-linux#21]
在linux中安装好了，但是不知道怎么切换节点

**Comment by ghostxu97** [comment]
在Linux版的Clash中，切换节点通常需要通过编辑配置文件或使用Clash的API。下面是两种主要方法来切换节点：通过编辑配置文件和使用Clash的RESTful API。

### 方法一：编辑配置文件
Clash的配置文件通常位于`~/.config/clash/config.yaml`。可以直接编辑这个文件来更改当前的节点。

1. 打开配置文件：
   ```bash
   nano ~/.config/clash/config.yaml
   ```

2. 找到`proxies`部分，这里列出了所有可用的代理节点。例如：
   ```yaml
   proxies:
     - name: "Proxy1"
       type: ss
       server: 1.2.3.4
       port: 8388
       cipher: AES-256-GCM
       password: "your_password"
     - name: "Proxy2"
       type: ss
       server: 5.6.7.8
       port: 8388
       cipher: AES-256-GCM
       password: "your_password"
   ```

3. 在`proxy-groups`部分，找到你正在使用的代理组，并更改`proxies`列表中的第一个代理名称为你想要切换的节点。例如：
   ```yaml
   proxy-groups:
     - name: "Proxy"
       type: select
       proxies:
         - "Proxy2"
         - "Proxy1"
   ```

4. 保存文件并退出（对于nano，按 `Ctrl+O` 然后 `Ctrl+X`）。

5. 重启Clash服务：
   ```bash
   systemctl restart clash
   ```

### 方法二：使用Clash的RESTful API
Clash提供了一个RESTful API，可以通过终端命令切换节点。

1. 确保Clash的RESTful API已启用。在你的`config.yaml`中启用API：
   ```yaml
   external-controller: 127.0.0.1:9090
   ```

2. 使用`curl`命令切换节点。假设你有一个名为“Proxy”的选择组，想切换到名为“Proxy2”的节点，可以使用以下命令：
   ```bash
   curl -X PUT "http://127.0.0.1:9090/proxies/Proxy" -H "Content-Type: application/json" -d '{"name": "Proxy2"}'
   ```

3. 确认切换成功：
   ```bash
   curl -X GET "http://127.0.0.1:9090/proxies/Proxy"
   ```

### 小结
通过这两种方法，你可以在Linux版的Clash中通过终端切换节点。编辑配置文件的方法适合手动操作，而使用RESTful API的方法则适合自动化或脚本操作。选择适合你的方法，根据需求灵活切换代理节点。
